[project]
name = "bsthackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.122.0",
    "loguru>=0.7.3",
    "openai>=2.8.1",
    "uvicorn>=0.38.0",
]
